spring.application.name=foodiesapi

#mongodb configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=foodies

#aws s3 configuration
aws.access.key=${AWS_ACCESS_KEY}
aws.secret.key=${AWS_SECRET_KEY}
aws.s3.region=eu-north-1
aws.s3.bucketname=foodie.foods

jwt.secret.key=q2NpY29sZSBzdGFja2V4Y2hhbmdlIGludGVybmF0aW9uYWxpemF0aW9uIHJvYm90cyBpbg==

iyzico.api.key=sandbox-V6pY8W6p9W9p8W6p9W6p9W6p9W6p9W6p
iyzico.secret.key=sandbox-V6pY8W6p9W9p8W6p9W6p9W6p9W6p9W6p
iyzico.base.url=https://sandbox-api.iyzipay.com